import type { ITableTranslations } from "../types";

export const translations: ITableTranslations = {
	toolbar: {
		clear: "Clear Filter",
		close: "Close",
		create: "Create",
		delete: "Delete",
		edit: "Edit",
		filterColumns: "Filter Columns",
		large: "Large",
		medium: "Medium",
		noDataAvailable: "No data available",
		refresh: "Refresh",
		rowsPerPage: "Rows per page",
		searchInputPlaceholder: "Search all",
		selectRowHeight: "Select row height",
		small: "Small",
	},
	header: {
		clearSort: "Clear Sort",
		filterColumn: "Filter Column",
		clearAll: "Clear all",
		selectAll: "Select all",
		clearPage: "Clear page",
		selectPage: "Select page",
		items: "items",
		tableSelectionDropdown: "Table Selection Dropdown",
		sortAscending: "A - Z",
		sortDescending: "Z - A",
		toggleSortBy: "Toggle SortBy",
		dragHandle: "Drag Handle",
	},
	body: {
		someItemsSelected: "Some items are selected.",
		pageSelected: "All items on this page are selected.",
		allSelected: "All items are selected.",
		clearSelection: "Clear all items in the table.",
		noDataAvailable: "no data available",
		selectAll: "Select all items in the table.",
	},
	pagination: {
		backIconButtonText: "back",
		nextIconButtonText: "next",
		itemsPerPageLabel: "SHOW: ",
		tooltipForCurrentPage: "current page",
		tooltipForShownPagesSelect: "items per page",
	},
};
