name: Generate Unit Test Coverage Report
on:
  [push]
  # push:
    # branches: main

jobs:
  build:
    name: generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: generate coverage report
        id: report
        run: yarn install && yarn build && yarn test:coverage

      - name: display coverage report highlights
        run: |
          echo "Coverage Percentage - ${{ steps.report.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.report.outputs.color }}"
          echo "Summary HTML - ${{ steps.report.outputs.summaryHtml }}"

      - name: create the badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e90dadd4c95bbcf46094100f6591134e
          filename: code-coverage.json
          label: code-coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: react
